### ISSUE TITLE
problem with the dataset from practical 8

### ISSUE THREAD

**Issue by anaismartins** [gerkovink/INFOMDA1-2022#57]
hey! it seems the website linked in practical 8 where you should get your data from has been updated or something? the dataset you can get now from there doesn't have a 'disease' variable. or am I getting the wrong data?

**Comment by gerkovink** [comment]
You can find the relevant test/train splits on the course page, right below the practical.

Here's a [direct link](https://www.gerkovink.com/slv/practicals/09_ensemble/data.zip)
